_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.9.6
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
epochs:
    value: 220414
lr:
    value: 0.0005579953221417061
